name: Docker Pull

on:
  repository_dispatch:
    types:
      - docker-pull

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker image
        run: |
          echo "Pulling image: ${{ github.event.client_payload.image }}"
          docker pull "${{ github.event.client_payload.image }}"

      - name: Show image
        run: |
          docker images "${{ github.event.client_payload.image }}"
      
      - name: Login Aliyun Registry
        env:
          ALIYUN_DOCKER_USERNAME: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          ALIYUN_DOCKER_PWD: ${{ secrets.ALIYUN_DOCKER_PWD }}
          ALIYUN_DOCKER_REGISTRY: ${{ secrets.ALIYUN_DOCKER_REGISTRY }}
        run: |
          echo "$ALIYUN_DOCKER_PWD" | docker login -u "$ALIYUN_DOCKER_USERNAME" --password-stdin "$ALIYUN_DOCKER_REGISTRY"
